name             'snort'
maintainer       'Sous Chefs'
maintainer_email 'help@sous-chefs.org'
license          'Apache-2.0'
description      'Installs Snort IDS packages'
version          '5.0.13'
chef_version     '>= 15.0'
source_url       'https://github.com/sous-chefs/snort'
issues_url       'https://github.com/sous-chefs/snort/issues'

supports 'ubuntu'
supports 'debian'
supports 'redhat'
supports 'centos'
supports 'fedora'
supports 'scientific'
supports 'amazon'
supports 'oracle'

depends 'yum-epel'
